import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Provider from "@/app/components/provider";
import Appbar from "@/app/components/appbar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <Provider>
          <Toaster position="top-right" reverseOrder={false} />
          <div className="w-full bg-zinc-200 h-screen">
            <div className=" ">
              <Appbar />
            </div>
            <div className=" flex w-full">
              <div className="w-full h-full"> {children}</div>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
